### ISSUE TITLE
(ERROR) Getting crashed while downloading (Details Inside)

### ISSUE THREAD

**Issue by NomanBaigA** [gitcoder-aman/Instagram-Video-Downloader#1]
Error Reason - You didnt ask for permission during app launch.

Error -

FATAL EXCEPTION: DefaultDispatcher-worker-1
                                                                                                    Process: com.tech.instasaver, PID: 28754
                                                                                                    java.io.FileNotFoundException: /storage/emulated/0/Download/InstaSaver/3208809926457363039.mp4 (No such file or directory)
                                                                                                    	at java.io.FileOutputStream.open0(Native Method)
                                                                                                    	at java.io.FileOutputStream.open(FileOutputStream.java:287)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
                                                                                                    	at com.tech.instasaver.downloadFile.DownloadFileKt$startDownloadTask$1.invokeSuspend(DownloadFile.kt:33)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

**Comment by gitcoder-aman** [comment]
I'll check that but physical device are not getting this error.thanks for report this error.

**Comment by NomanBaigA** [comment]
> I'll check that but physical device are not getting this error.thanks for report this error.

I tested it with one physical device and one emulator. Same error with both

**Comment by NomanBaigA** [comment]
> I'll check that but physical device are not getting this error.thanks for report this error.

You can solve it easily you just have to ask for storage permission.

**Comment by gitcoder-aman** [comment]
I'm using an android 13 physical device so, I'm not getting this type of error but below Android 13 then getting the problem "permission denied" but I have now resolved it.

**Comment by NomanBaigA** [comment]
> I'm using an android 13 physical device so, I'm not getting this type of error but below Android 13 then getting the problem "permission denied" but I have now resolved it.

Ok Cool, I just teased it's working fine now
